-- 升级件草案：独立知识库模块（knowledge-base）T-01 → 里程碑归位预期编号 V1.3.0_02
-- 目标库：PostgreSQL（phoenix）
-- 幂等：CREATE TABLE/INDEX IF NOT EXISTS / ADD COLUMN IF NOT EXISTS / 迁移段全 NOT EXISTS 守卫，可重跑
-- 顺序：①库表 ②条目加列 ③绑定表 ④组×库表 ⑤菜单+ACL ⑥存量迁移
-- 回滚：见 02_knowledge_base_rollback.sql（drop 新表/新列/菜单，条目数据无损）
--
-- 语义注记（plan §1/P3/P6/A-06 实证）：
--   · 迁移自动建库 description='MIGRATED_FROM_AGENT:{agentId}' 为幂等锚点与溯源标记，A-06 命名「{agent名}的知识库」
--   · 条目表 agent_id 保留为溯源冗余，查询侧自 T-06 起不再使用
--   · group_kbase_info 与 tbl_platform_group_agent_info 同构，但 kbase_id 用 bigint（对齐库主键，join 免转型）

-- ① 知识库实体
CREATE TABLE IF NOT EXISTS tbl_data_knowledge_base (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(64)  NOT NULL,
    description  varchar(512),
    status       smallint     NOT NULL DEFAULT 1,
    creator      varchar(64),
    updator      varchar(64),
    del_flag     smallint     NOT NULL DEFAULT 0,
    create_time  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE  tbl_data_knowledge_base IS '独立知识库（knowledge-base spec R-01）';
COMMENT ON COLUMN tbl_data_knowledge_base.description IS '普通库=用户描述；迁移库=MIGRATED_FROM_AGENT:{id} 幂等锚';
COMMENT ON COLUMN tbl_data_knowledge_base.status IS '1启用 0停用；停用库整体不参与召回（A-03/R-09）';
CREATE UNIQUE INDEX IF NOT EXISTS uk_dkb_name_alive ON tbl_data_knowledge_base (name) WHERE del_flag = 0;

-- ② 条目表加库归属；agent_id 放掉 NOT NULL（新 kb 条目无归属 agent，agent_id 仅存量溯源；幂等）
ALTER TABLE tbl_data_agent_knowledge ADD COLUMN IF NOT EXISTS knowledge_base_id bigint;
ALTER TABLE tbl_data_agent_knowledge ALTER COLUMN agent_id DROP NOT NULL;
COMMENT ON COLUMN tbl_data_agent_knowledge.knowledge_base_id IS '归属知识库；agent_id 降级为溯源冗余（T-06 起查询不用）';
CREATE INDEX IF NOT EXISTS idx_dak_kb ON tbl_data_agent_knowledge (knowledge_base_id, is_deleted);

-- ③ 智能体×库 绑定（多对多，Q2）
CREATE TABLE IF NOT EXISTS tbl_data_agent_kbase_bind (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id          bigint       NOT NULL,
    knowledge_base_id bigint       NOT NULL,
    creator           varchar(64),
    create_time       timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_agent_kbase UNIQUE (agent_id, knowledge_base_id)
);
COMMENT ON TABLE tbl_data_agent_kbase_bind IS '智能体↔知识库绑定（R-08）；删 agent 仅清绑定不删库/条目（P6）';
CREATE INDEX IF NOT EXISTS idx_dakb_agent ON tbl_data_agent_kbase_bind (agent_id);

-- ④ 组×库 授权（platform 域，同构 group_agent，Q3/R-13）
CREATE TABLE IF NOT EXISTS tbl_platform_group_kbase_info (
    id         character varying(64) PRIMARY KEY,
    group_id   character varying(64) NOT NULL,
    kbase_id   bigint                NOT NULL,
    creator    character varying(64),
    updator    character varying(64),
    del_flag   smallint NOT NULL DEFAULT 0,
    create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_gki_group ON tbl_platform_group_kbase_info (group_id, del_flag);
CREATE INDEX IF NOT EXISTS idx_gki_kbase ON tbl_platform_group_kbase_info (kbase_id, del_flag);

-- ⑤ 菜单：知识库（与智能体管理同级 pid=NULL，R-02）+ ACL 复制自「智能体列表」模块既有授权角色
INSERT INTO tbl_privilege_module (id, pid, name, url, sn, component, type, order_no, is_show, status,
                                  image, create_time, del_flag)
SELECT md5('phoenix-knowledge-base-menu'), NULL, '知识库', '/knowledge-base', 'KnowledgeBase',
       '#/views/knowledge-base/index.vue', 1, 16, 1, 1, 'lucide:book-open', now(), 0
WHERE NOT EXISTS (SELECT 1 FROM tbl_privilege_module WHERE url = '/knowledge-base' AND del_flag = 0);

INSERT INTO tbl_privilege_acl (id, release_id, release_sn, system_sn, module_id, module_sn, acl_state,
                               create_time, del_flag)
SELECT gen_random_uuid()::text, x.release_id, x.release_sn, x.system_sn,
       md5('phoenix-knowledge-base-menu'), 'KnowledgeBase', x.acl_state, now(), 0
FROM tbl_privilege_acl x
WHERE x.module_id = 'f0c0d2d3a7bb452cb5ff98328575b41a' AND x.del_flag = 0
  AND NOT EXISTS (SELECT 1 FROM tbl_privilege_acl y
                  WHERE y.module_id = md5('phoenix-knowledge-base-menu') AND y.release_id = x.release_id AND y.del_flag = 0);

-- ⑥ 存量迁移：每个有未删条目的 agent → 自动建库 → 建绑定 → 条目回填 kb_id
INSERT INTO tbl_data_knowledge_base (name, description, status, creator, create_time, update_time)
SELECT a.name || '的知识库', 'MIGRATED_FROM_AGENT:' || a.id, 1, 'system', now(), now()
FROM (SELECT DISTINCT agent_id FROM tbl_data_agent_knowledge WHERE is_deleted = 0 AND agent_id IS NOT NULL) ka
JOIN tbl_data_agent a ON a.id = ka.agent_id
WHERE NOT EXISTS (SELECT 1 FROM tbl_data_knowledge_base b
                  WHERE b.description = 'MIGRATED_FROM_AGENT:' || a.id);

INSERT INTO tbl_data_agent_kbase_bind (agent_id, knowledge_base_id, creator, create_time)
SELECT a.id, b.id, 'system', now()
FROM (SELECT DISTINCT agent_id FROM tbl_data_agent_knowledge WHERE is_deleted = 0 AND agent_id IS NOT NULL) ka
JOIN tbl_data_agent a ON a.id = ka.agent_id
JOIN tbl_data_knowledge_base b ON b.description = 'MIGRATED_FROM_AGENT:' || a.id
WHERE NOT EXISTS (SELECT 1 FROM tbl_data_agent_kbase_bind x
                  WHERE x.agent_id = a.id AND x.knowledge_base_id = b.id);

UPDATE tbl_data_agent_knowledge k
   SET knowledge_base_id = b.id
  FROM tbl_data_knowledge_base b
 WHERE b.description = 'MIGRATED_FROM_AGENT:' || k.agent_id
   AND k.knowledge_base_id IS NULL AND k.is_deleted = 0;
